import json


class Post:
    def __init__(self, setting_str=None):
        if setting_str:
            self.load_post(setting_str)
        else:
            self.id = None  # post id
            self.text = None  # content of the post
            self.title = None  # title of the post
            self.post_type = None  # type of the post, 1 for question post, 2 for answer post
            self.published = None  # published datetime of the post
            self.internal_links = None  # contain links within bleeping computers (starts with http://www.bleepingcomputer.com)
            self.external_links = None  # contain links of external files
            self.tags = None  # keywords of the question. Generated by BleepingComputers

    def export_post(self):
        return json.dumps(self.__dict__)

    def load_post(self, setting_str):
        self.__dict__ = json.loads(setting_str)

    def print(self):
        print(self.export_post())